/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import controller.ControllerConta;
import controller.ControllerFornecedor;
import controller.ControllerTipoPagamento;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.ModelConta;
import model.ModelFornecedor;
import model.ModelTipoPagamento;
import util.BLDatas;

/**
 *
 * @author Administrador
 */
public class ViewContasReceber extends javax.swing.JFrame {
    ModelConta modelConta = new ModelConta();
    ControllerFornecedor controllerFornecedor = new ControllerFornecedor();
    ArrayList<ModelConta> listaModelConta = new ArrayList<>();
    ControllerConta controllerConta = new ControllerConta();
    ControllerTipoPagamento controllerTipoPagamento = new ControllerTipoPagamento();
    ArrayList<ModelTipoPagamento> listaModelTipoPagamentos = new ArrayList<>();
    ArrayList<ModelFornecedor> listaModelFornecedor = new ArrayList<>();
    String tipoCadastro;
    /**
     * Creates new form ViewContasPagar
     */
    public ViewContasReceber() {
        initComponents();
        setLocationRelativeTo(null);
        this.limparDados();
        this.habilitaDesabilitarCampos(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jtfPesquisa2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jbPesquisar2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbContasReceber = new javax.swing.JTable();
        btCancelar = new javax.swing.JButton();
        jbExcluirPagar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();
        jbVisualizarPagar1 = new javax.swing.JButton();
        jbReceberConta = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btCancelar1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbContasRecebidas = new javax.swing.JTable();
        jtfPesquisa1 = new javax.swing.JTextField();
        jbPesquisar1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jbVisualizarPagar2 = new javax.swing.JButton();
        jpRevorgarConta = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jcbClientes = new componentes.UJComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelPagamento = new javax.swing.JLabel();
        jtfValor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfDescricao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jcbTipoPagamento = new componentes.UJComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtfObservacao = new javax.swing.JTextPane();
        jLabel10 = new javax.swing.JLabel();
        btCancelar2 = new javax.swing.JButton();
        jdData = new com.toedter.calendar.JDateChooser();
        jdVencimento = new com.toedter.calendar.JDateChooser();
        jdPagamento = new com.toedter.calendar.JDateChooser();
        JbSAlvar = new javax.swing.JButton();
        jtfCodigoConta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Contas a receber");

        jLabel1.setText("Descrição:");

        jbPesquisar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/Search.png"))); // NOI18N
        jbPesquisar2.setText("Pesquisar");
        jbPesquisar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisar2ActionPerformed(evt);
            }
        });

        tbContasReceber.setAutoCreateRowSorter(true);
        tbContasReceber.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Descrição", "Cliente", "Data", "Vencimento", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbContasReceber.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tbContasReceber.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tbContasReceber);
        if (tbContasReceber.getColumnModel().getColumnCount() > 0) {
            tbContasReceber.getColumnModel().getColumn(0).setMinWidth(50);
            tbContasReceber.getColumnModel().getColumn(0).setMaxWidth(50);
            tbContasReceber.getColumnModel().getColumn(1).setMinWidth(200);
            tbContasReceber.getColumnModel().getColumn(2).setMinWidth(200);
        }

        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/No.png"))); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        jbExcluirPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/Delete.png"))); // NOI18N
        jbExcluirPagar.setText("Excluir");
        jbExcluirPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirPagarActionPerformed(evt);
            }
        });

        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/Modify.png"))); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/Add.png"))); // NOI18N
        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        jbVisualizarPagar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/Report.png"))); // NOI18N
        jbVisualizarPagar1.setText("Visualizar/Imprimir");
        jbVisualizarPagar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVisualizarPagar1ActionPerformed(evt);
            }
        });

        jbReceberConta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/Apply.png"))); // NOI18N
        jbReceberConta.setText("Receber conta");
        jbReceberConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbReceberContaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbExcluirPagar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbReceberConta))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jtfPesquisa2, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbPesquisar2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbVisualizarPagar1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPesquisa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPesquisar2)
                    .addComponent(jbVisualizarPagar1))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btNovo)
                    .addComponent(btAlterar)
                    .addComponent(btCancelar)
                    .addComponent(jbExcluirPagar)
                    .addComponent(jbReceberConta))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Contas a receber", jPanel3);

        btCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/No.png"))); // NOI18N
        btCancelar1.setText("Cancelar");
        btCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelar1ActionPerformed(evt);
            }
        });

        tbContasRecebidas.setAutoCreateRowSorter(true);
        tbContasRecebidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Descrição", "Cliente", "Data", "Vencimento", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbContasRecebidas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tbContasRecebidas.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tbContasRecebidas);
        if (tbContasRecebidas.getColumnModel().getColumnCount() > 0) {
            tbContasRecebidas.getColumnModel().getColumn(0).setMinWidth(50);
            tbContasRecebidas.getColumnModel().getColumn(0).setMaxWidth(50);
            tbContasRecebidas.getColumnModel().getColumn(1).setMinWidth(200);
            tbContasRecebidas.getColumnModel().getColumn(2).setMinWidth(200);
        }

        jbPesquisar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/Search.png"))); // NOI18N
        jbPesquisar1.setText("Pesquisar");
        jbPesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisar1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Descrição:");

        jbVisualizarPagar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/Report.png"))); // NOI18N
        jbVisualizarPagar2.setText("Visualizar/Imprimir");
        jbVisualizarPagar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVisualizarPagar2ActionPerformed(evt);
            }
        });

        jpRevorgarConta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/Erase.png"))); // NOI18N
        jpRevorgarConta.setText("Revogar recebimento");
        jpRevorgarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpRevorgarContaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jtfPesquisa1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbPesquisar1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbVisualizarPagar2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btCancelar1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jpRevorgarConta)))
                        .addGap(116, 116, 116))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(109, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPesquisa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPesquisar1)
                    .addComponent(jbVisualizarPagar2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 320, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelar1)
                    .addComponent(jpRevorgarConta))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(73, 73, 73)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(55, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Contas recebidas", jPanel2);

        jLabel2.setText("Fornecedor:");

        jLabel6.setText("Data:");

        jLabel7.setText("Vencimento:");

        labelPagamento.setText("Data Pagamento:");

        jtfValor.setBackground(new java.awt.Color(51, 255, 204));

        jLabel3.setText("Valor:");

        jLabel4.setText("Descrição da conta:");

        jLabel8.setText("Tipo de pagamento:");

        jScrollPane1.setViewportView(jtfObservacao);

        jLabel10.setText("Observação:");

        btCancelar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/No.png"))); // NOI18N
        btCancelar2.setText("Cancelar");
        btCancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelar2ActionPerformed(evt);
            }
        });

        JbSAlvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/Save.png"))); // NOI18N
        JbSAlvar.setText("Salvar");
        JbSAlvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbSAlvarActionPerformed(evt);
            }
        });

        jtfCodigoConta.setEditable(false);
        jtfCodigoConta.setBackground(new java.awt.Color(204, 255, 204));
        jtfCodigoConta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel5.setText("Código da conta:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btCancelar2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JbSAlvar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfDescricao, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jcbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jtfCodigoConta))))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8)
                            .addComponent(jcbTipoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jdData, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jdVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelPagamento)
                                    .addComponent(jdPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jtfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCodigoConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel6))
                                    .addComponent(jLabel7)
                                    .addComponent(labelPagamento)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jtfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jdData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jdPagamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jdVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbTipoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelar2)
                    .addComponent(JbSAlvar))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cadastro", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        // habilita ou desabilita campos
        this.limparDados();
        this.habilitaDesabilitarCampos(false);
    }//GEN-LAST:event_btCancelarActionPerformed

    private void jbExcluirPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirPagarActionPerformed
        this.excluirConta();
    }//GEN-LAST:event_jbExcluirPagarActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        try {
            int linha = tbContasReceber.getSelectedRow();
            int codigo = (int) tbContasReceber.getValueAt(linha, 0);
            this.limparDados();
            this.habilitaDesabilitarCampos(true);
            tipoCadastro = "alteracao";
            //seta o código para alteração
            recuperarConta(codigo);
            //avançar para aba 3
            jTabbedPane1.setSelectedIndex(jTabbedPane1.getSelectedIndex() + 2);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Você selecionar uma conta para alterar!", "ATENÇÂO", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        // TODO add your handling code here:
        this.limparDados();
        this.habilitaDesabilitarCampos(true);
        tipoCadastro = "cadastro";
        this.jtfCodigoConta.setText("Nova Conta");
        //avançar para aba 3
        jTabbedPane1.setSelectedIndex(jTabbedPane1.getSelectedIndex() + 2);
    }//GEN-LAST:event_btNovoActionPerformed

    private void btCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelar1ActionPerformed
        // TODO add your handling code here:
        this.limparDados();
        this.habilitaDesabilitarCampos(false);
    }//GEN-LAST:event_btCancelar1ActionPerformed

    private void btCancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelar2ActionPerformed
        // TODO add your handling code here:
        this.limparDados();
        this.habilitaDesabilitarCampos(false);
        jTabbedPane1.setSelectedIndex(jTabbedPane1.getSelectedIndex() - 2);
    }//GEN-LAST:event_btCancelar2ActionPerformed

    private void JbSAlvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbSAlvarActionPerformed
        if (jtfDescricao.getText().equals("") || jtfValor.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Você deve preencher todos os campos!", "ATENÇÂO", JOptionPane.WARNING_MESSAGE);
        }else{
            if(tipoCadastro.equals("cadastro")){
                this.salvar();
                jTabbedPane1.setSelectedIndex(jTabbedPane1.getSelectedIndex() - 2);
            }else{
                this.alterar();
                jTabbedPane1.setSelectedIndex(jTabbedPane1.getSelectedIndex() - 2);
            }
        }
    }//GEN-LAST:event_JbSAlvarActionPerformed

    private void jbPesquisar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisar2ActionPerformed
        DefaultTableModel tabela = (DefaultTableModel) this.tbContasReceber.getModel();
        final TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tabela);
        this.tbContasReceber.setRowSorter(sorter);
        String text = jtfPesquisa2.getText();
        sorter.setRowFilter(RowFilter.regexFilter(text, 1));
    }//GEN-LAST:event_jbPesquisar2ActionPerformed

    private void jbPesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisar1ActionPerformed
        DefaultTableModel tabela = (DefaultTableModel) this.tbContasRecebidas.getModel();
        final TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tabela);
        this.tbContasRecebidas.setRowSorter(sorter);
        String text = jtfPesquisa1.getText();
        sorter.setRowFilter(RowFilter.regexFilter(text, 1));
    }//GEN-LAST:event_jbPesquisar1ActionPerformed

    private void jbVisualizarPagar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVisualizarPagar1ActionPerformed
        int linha = tbContasRecebidas.getSelectedRow();
        int codigo = (int) tbContasRecebidas.getValueAt(linha, 0);
        controllerConta.gerarRelatorioContaReceber(codigo);
    }//GEN-LAST:event_jbVisualizarPagar1ActionPerformed

    private void jbVisualizarPagar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVisualizarPagar2ActionPerformed
        int linha = tbContasRecebidas.getSelectedRow();
        int codigo = (int) tbContasRecebidas.getValueAt(linha, 0);
        controllerConta.gerarRelatorioContaReceber(codigo);
    }//GEN-LAST:event_jbVisualizarPagar2ActionPerformed

    private void jbReceberContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbReceberContaActionPerformed
       modelConta = new ModelConta();
        try {
            int linha = tbContasReceber.getSelectedRow();
            int codigo = (int) tbContasReceber.getValueAt(linha, 0);
            BLDatas bl = new BLDatas();
            
            modelConta.setCodigo(codigo);
            modelConta.setSituacao(1);
            modelConta.setPagamento(bl.converterDataParaDateUS(new java.util.Date(System.currentTimeMillis())));
            //pegunta
            int opcao = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja"
                    + " receber a conta nº:\n" + "\n " + codigo + "?", "Atenção", JOptionPane.YES_NO_OPTION);
            //se sim recebe, se não não faz nada
            if (opcao == JOptionPane.OK_OPTION) {
                if (controllerConta.receberContaReceberController(modelConta)) {
                    JOptionPane.showMessageDialog(this, "Conta Recebida!");
                    this.carregarContasReceber();
                    this.carregarContasRecebidas();
                }
            }

            jTabbedPane1.setSelectedIndex(jTabbedPane1.getSelectedIndex() + 1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Você deve selecionar uma conta!", "ATENÇÂO", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jbReceberContaActionPerformed

    private void jpRevorgarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpRevorgarContaActionPerformed
       modelConta = new ModelConta();
        try {
            int linha = tbContasRecebidas.getSelectedRow();
            int codigo = (int) tbContasRecebidas.getValueAt(linha, 0);
            BLDatas bl = new BLDatas();
            
            modelConta.setCodigo(codigo);
            modelConta.setSituacao(0);
            modelConta.setPagamento(bl.converterDataParaDateUS(new java.util.Date(System.currentTimeMillis())));
            //pegunta
            int opcao = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja"
                    + " revogar o recebimento da conta nº:\n" + "\n " + codigo + "?", "Atenção", JOptionPane.YES_NO_OPTION);
            //se sim revoga, se não não faz nada
            if (opcao == JOptionPane.OK_OPTION) {
                if (controllerConta.receberContaReceberController(modelConta)) {
                    JOptionPane.showMessageDialog(this, "Conta revogada!");
                    this.carregarContasReceber();
                    this.carregarContasRecebidas();
                }
            }

            jTabbedPane1.setSelectedIndex(jTabbedPane1.getSelectedIndex() - 1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Você deve selecionar uma conta!", "ATENÇÂO", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jpRevorgarContaActionPerformed
  
    /**
     * REcuperar dados do banco para alterar
     *
     * @param pCodigoConta
     * @return
     */
    private boolean recuperarConta(int pCodigoConta) {
        modelConta = new ModelConta();
        modelConta = controllerConta.getContaPagarController(pCodigoConta);
        this.jcbClientes.setSelectedItem(controllerFornecedor.getFornecedorController(modelConta.getCodigoPessoa()).getNome());
        this.jtfCodigoConta.setText(String.valueOf(pCodigoConta));
        this.jtfDescricao.setText(modelConta.getDescricao());
        this.jdData.setDate(modelConta.getData());
        this.jdPagamento.setDate(modelConta.getPagamento());
        this.jdVencimento.setDate(modelConta.getVencimento());
        this.jtfValor.setText(String.valueOf(modelConta.getValor()));
        this.jcbTipoPagamento.setSelectedItem(controllerTipoPagamento.getTipoPagamentoController(modelConta.getTipoPagamento()).getDescricao());
        return true;
    }
    
    /**
     * Excluir dados do banco
     * @return 
     */
    private boolean excluirConta() {
        int linha = tbContasReceber.getSelectedRow();
        String nome = (String) tbContasReceber.getValueAt(linha, 1);
        int codigo = (int) tbContasReceber.getValueAt(linha, 0);

        //pegunta se realmente deseja excluir
        int opcao = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja"
                + " excluir o registro:\n" + "\n " + nome + "?", "Atenção", JOptionPane.YES_NO_OPTION);
        //se sim exclui, se não não faz nada
        if (opcao == JOptionPane.OK_OPTION) {
            if (controllerConta.excluirContaPagarController(codigo)) {
                JOptionPane.showMessageDialog(this, "Registro excluido com suscesso!");
                carregarContasReceber();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao e os dados!", "ERRO", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }
        return true;
    }
    
    /**
     * Salvar dados
     * @return 
     */
    private boolean salvar() {
        BLDatas bl = new BLDatas();
        modelConta.setTipoConta("RECEBER");
        modelConta.setCodigoPessoa(controllerFornecedor.getFornecedorController(this.jcbClientes.getSelectedItem().toString()).getCodigo());
        modelConta.setDescricao(this.jtfDescricao.getText());
        try {
            modelConta.setData(bl.converterDataParaDateUS(jdData.getDate()));
            modelConta.setVencimento(bl.converterDataParaDateUS(jdVencimento.getDate()));
            modelConta.setPagamento(bl.converterDataParaDateUS(jdPagamento.getDate()));
        } catch (Exception ex) {
            Logger.getLogger(ViewVenda.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        modelConta.setSituacao(0);
        modelConta.setValor(Float.parseFloat(this.jtfValor.getText()));
        modelConta.setTipoPagamento(controllerTipoPagamento.getTipoPagamentoController(this.jcbTipoPagamento.getSelectedItem().toString()).getCodigo());
        modelConta.setObservacao(this.jtfObservacao.getText());

        //salvar 
        if (controllerConta.salvarContaPagarController(modelConta)>0) {
            JOptionPane.showMessageDialog(this, "Registro gravado com sucesso!");
            this.limparDados();
            this.habilitaDesabilitarCampos(false);
            this.carregarContasReceber();
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao gravar os dados!", "ERRO", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }
    
   /**
     * Alterar dados
     * @return 
     */
    private boolean alterar() {
        BLDatas bl = new BLDatas();
        modelConta.setTipoConta("RECEBER");
        modelConta.setCodigoPessoa(controllerFornecedor.getFornecedorController(this.jcbClientes.getSelectedItem().toString()).getCodigo());
        modelConta.setDescricao(this.jtfDescricao.getText());
        modelConta.setCodigo(Integer.parseInt(this.jtfCodigoConta.getText()));
        try {
            modelConta.setData(bl.converterDataParaDateUS(jdData.getDate()));
            modelConta.setVencimento(bl.converterDataParaDateUS(jdVencimento.getDate()));
            modelConta.setPagamento(bl.converterDataParaDateUS(jdPagamento.getDate()));
        } catch (Exception ex) {
            Logger.getLogger(ViewVenda.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        modelConta.setSituacao(0);
        modelConta.setValor(Float.parseFloat(this.jtfValor.getText()));
        modelConta.setTipoPagamento(controllerTipoPagamento.getTipoPagamentoController(this.jcbTipoPagamento.getSelectedItem().toString()).getCodigo());
        modelConta.setObservacao(this.jtfObservacao.getText());

        //salvar 
        if (controllerConta.atualizarContaPagarController(modelConta)) {
            JOptionPane.showMessageDialog(this, "Registro alterado com sucesso!");
            this.limparDados();
            this.habilitaDesabilitarCampos(false);
            this.carregarContasReceber();
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao alterar os dados!", "ERRO", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }
    
     private void carregarContasReceber() {
        listaModelConta = controllerConta.getListaContaReceberController(0);
        DefaultTableModel modelo = (DefaultTableModel) tbContasReceber.getModel();
        modelo.setNumRows(0);
        String nomeCliente;
        //CARREGA OS DADOS DA LISTA NA TABELA
        int cont = listaModelConta.size();
        for (int i = 0; i < cont; i++) {
            nomeCliente = controllerFornecedor.getFornecedorController(listaModelConta.get(i).getCodigoPessoa()).getNome();
            modelo.addRow(new Object[]{
                listaModelConta.get(i).getCodigo(),
                listaModelConta.get(i).getDescricao(),
                nomeCliente,
                listaModelConta.get(i).getData(),
                listaModelConta.get(i).getVencimento(),
                listaModelConta.get(i).getValor()
            });
        }
    }
    
     private void carregarContasRecebidas() {
        listaModelConta = controllerConta.getListaContaReceberController(1);
        DefaultTableModel modelo = (DefaultTableModel) tbContasRecebidas.getModel();
        modelo.setNumRows(0);
        String nomeCliente;
        //CARREGA OS DADOS DA LISTA NA TABELA
        int cont = listaModelConta.size();
        for (int i = 0; i < cont; i++) {
            nomeCliente = controllerFornecedor.getFornecedorController(listaModelConta.get(i).getCodigoPessoa()).getNome();
            modelo.addRow(new Object[]{
                listaModelConta.get(i).getCodigo(),
                listaModelConta.get(i).getDescricao(),
                nomeCliente,
                listaModelConta.get(i).getData(),
                listaModelConta.get(i).getVencimento(),
                listaModelConta.get(i).getValor()
            });
        }
    }
     
    private void listarClientes(){
        listaModelFornecedor = controllerFornecedor.getListaFornecedorController();
        jcbClientes.removeAllItems();
        for (int i = 0; i < listaModelFornecedor.size(); i++){
            jcbClientes.addItem(listaModelFornecedor.get(i).getNome());
        }
    }
    
    private void listarTipoPagamento(){
        listaModelTipoPagamentos = controllerTipoPagamento.getListaTipoPagamentoController();
        jcbTipoPagamento.removeAllItems();
        for (int i = 0; i < listaModelTipoPagamentos.size(); i++){
            jcbTipoPagamento.addItem(listaModelTipoPagamentos.get(i).getDescricao());
        }
    }
    
    
    private void limparDados(){
        listarClientes();
        listarTipoPagamento();
        carregarContasReceber();
        carregarContasRecebidas();
        this.jtfDescricao.setText("");
        this.jtfObservacao.setText("");
        this.jtfValor.setText("");
        this.jdData.setDate(null);
        this.jdPagamento.setDate(null);
        this.jdVencimento.setDate(null);
       
    }
    
    /**
     * Habilitar ou desabilitar campos do formulário
     * @param operaco 
     */
    private void habilitaDesabilitarCampos(boolean operaco){
        this.jtfDescricao.setEnabled(operaco);
        this.jtfObservacao.setEnabled(operaco);
        this.jtfValor.setEnabled(operaco);
        this.jcbTipoPagamento.setEnabled(operaco);
        this.jdData.setEnabled(operaco);
        this.jdPagamento.setEnabled(operaco);
        this.jdVencimento.setEnabled(operaco);
        this.jcbClientes.setEnabled(operaco);
        this.JbSAlvar.setEnabled(operaco);
    
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewContasReceber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewContasReceber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewContasReceber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewContasReceber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewContasReceber().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbSAlvar;
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btCancelar1;
    private javax.swing.JButton btCancelar2;
    private javax.swing.JButton btNovo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbExcluirPagar;
    private javax.swing.JButton jbPesquisar1;
    private javax.swing.JButton jbPesquisar2;
    private javax.swing.JButton jbReceberConta;
    private javax.swing.JButton jbVisualizarPagar1;
    private javax.swing.JButton jbVisualizarPagar2;
    private componentes.UJComboBox jcbClientes;
    private componentes.UJComboBox jcbTipoPagamento;
    private com.toedter.calendar.JDateChooser jdData;
    private com.toedter.calendar.JDateChooser jdPagamento;
    private com.toedter.calendar.JDateChooser jdVencimento;
    private javax.swing.JButton jpRevorgarConta;
    private javax.swing.JTextField jtfCodigoConta;
    private javax.swing.JTextField jtfDescricao;
    private javax.swing.JTextPane jtfObservacao;
    private javax.swing.JTextField jtfPesquisa1;
    private javax.swing.JTextField jtfPesquisa2;
    private javax.swing.JTextField jtfValor;
    private javax.swing.JLabel labelPagamento;
    private javax.swing.JTable tbContasReceber;
    private javax.swing.JTable tbContasRecebidas;
    // End of variables declaration//GEN-END:variables
}
