/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import controller.ControllerCliente;
import controller.ControllerFornecedor;
import controller.ControllerProdutos;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.ModelSessaoUsuario;
import util.BLDatas;

/**
 *
 * @author Br
 */
public class ViewPrincipal extends javax.swing.JFrame {
    
    String pNomeUsuario;

    /**
     * Creates new form ViewPrincipal
     */
    public ViewPrincipal() {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        configurar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        uJPanelImagem1 = new componentes.UJPanelImagem();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        btClientes = new javax.swing.JButton();
        btProdutos = new javax.swing.JButton();
        btFornecedores = new javax.swing.JButton();
        btUsuario = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btRegistrarVenda = new javax.swing.JButton();
        btRegistrarVenda1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btContaspagar = new javax.swing.JButton();
        btContasReceber = new javax.swing.JButton();
        btFluxoCaixa = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jbRelatorioVendas = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jlUsuario = new javax.swing.JLabel();
        jlData = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmArquivo = new javax.swing.JMenu();
        jmiSobre = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        mnuSair = new javax.swing.JMenuItem();
        jmCadastrar = new javax.swing.JMenu();
        jmiClientes = new javax.swing.JMenuItem();
        jmiProdutos = new javax.swing.JMenuItem();
        jmiFornecedor = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmVendas = new javax.swing.JMenu();
        mnuRegistrarVenda = new javax.swing.JMenuItem();
        jmiConsultarVenda = new javax.swing.JMenuItem();
        jmiPdv = new javax.swing.JMenuItem();
        jmFinanceiro = new javax.swing.JMenu();
        jmiContasPagar = new javax.swing.JMenuItem();
        jmiContasReceber = new javax.swing.JMenuItem();
        jmiFluxoCaixa = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmiRelClientes = new javax.swing.JMenuItem();
        jmiRelFornecedor = new javax.swing.JMenuItem();
        jmiRelProdutos = new javax.swing.JMenuItem();
        jmiRelatorioVendas = new javax.swing.JMenuItem();
        jmiRelatorioVenda = new javax.swing.JMenuItem();
        jmAjuda = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("jMenu4");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BLVendas");

        uJPanelImagem1.setImagem(new java.io.File("C:\\BLVendasPdvMySQL\\src\\imagens\\software.jpg"));

        jToolBar1.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu rápido", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, null, new java.awt.Color(102, 102, 102)));
        jToolBar1.setForeground(new java.awt.Color(102, 102, 102));
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("Cadastro");
        jToolBar1.add(jLabel1);

        btClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/User group.png"))); // NOI18N
        btClientes.setText("Clientes");
        btClientes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btClientes.setMaximumSize(new java.awt.Dimension(200, 40));
        btClientes.setMinimumSize(new java.awt.Dimension(200, 40));
        btClientes.setPreferredSize(new java.awt.Dimension(200, 40));
        btClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClientesActionPerformed(evt);
            }
        });
        jToolBar1.add(btClientes);

        btProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/Component.png"))); // NOI18N
        btProdutos.setText("Produtos");
        btProdutos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btProdutos.setMaximumSize(new java.awt.Dimension(200, 40));
        btProdutos.setMinimumSize(new java.awt.Dimension(200, 40));
        btProdutos.setPreferredSize(new java.awt.Dimension(200, 40));
        btProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProdutosActionPerformed(evt);
            }
        });
        jToolBar1.add(btProdutos);

        btFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/Boss.png"))); // NOI18N
        btFornecedores.setText("Fornecedor");
        btFornecedores.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btFornecedores.setMaximumSize(new java.awt.Dimension(200, 40));
        btFornecedores.setMinimumSize(new java.awt.Dimension(200, 40));
        btFornecedores.setPreferredSize(new java.awt.Dimension(200, 40));
        btFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFornecedoresActionPerformed(evt);
            }
        });
        jToolBar1.add(btFornecedores);

        btUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/People.png"))); // NOI18N
        btUsuario.setText("Usuário");
        btUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btUsuario.setMaximumSize(new java.awt.Dimension(200, 40));
        btUsuario.setMinimumSize(new java.awt.Dimension(200, 40));
        btUsuario.setPreferredSize(new java.awt.Dimension(200, 40));
        btUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUsuarioActionPerformed(evt);
            }
        });
        jToolBar1.add(btUsuario);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setText("Saida");
        jToolBar1.add(jLabel2);

        btRegistrarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/Shopping cart.png"))); // NOI18N
        btRegistrarVenda.setText("Registrar venda");
        btRegistrarVenda.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btRegistrarVenda.setMaximumSize(new java.awt.Dimension(200, 40));
        btRegistrarVenda.setMinimumSize(new java.awt.Dimension(200, 40));
        btRegistrarVenda.setPreferredSize(new java.awt.Dimension(200, 40));
        btRegistrarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarVendaActionPerformed(evt);
            }
        });
        jToolBar1.add(btRegistrarVenda);

        btRegistrarVenda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/Shopping cart.png"))); // NOI18N
        btRegistrarVenda1.setText("PDV");
        btRegistrarVenda1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btRegistrarVenda1.setFocusable(false);
        btRegistrarVenda1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btRegistrarVenda1.setMaximumSize(new java.awt.Dimension(200, 40));
        btRegistrarVenda1.setMinimumSize(new java.awt.Dimension(200, 40));
        btRegistrarVenda1.setPreferredSize(new java.awt.Dimension(200, 40));
        btRegistrarVenda1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btRegistrarVenda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarVenda1ActionPerformed(evt);
            }
        });
        jToolBar1.add(btRegistrarVenda1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 0));
        jLabel3.setText("Financeiro");
        jToolBar1.add(jLabel3);

        btContaspagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/Upload.png"))); // NOI18N
        btContaspagar.setText("Contas a pagar");
        btContaspagar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btContaspagar.setFocusable(false);
        btContaspagar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btContaspagar.setMaximumSize(new java.awt.Dimension(200, 40));
        btContaspagar.setMinimumSize(new java.awt.Dimension(200, 40));
        btContaspagar.setPreferredSize(new java.awt.Dimension(200, 40));
        btContaspagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btContaspagarActionPerformed(evt);
            }
        });
        jToolBar1.add(btContaspagar);

        btContasReceber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/Download.png"))); // NOI18N
        btContasReceber.setText("Contas a receber");
        btContasReceber.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btContasReceber.setFocusable(false);
        btContasReceber.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btContasReceber.setMaximumSize(new java.awt.Dimension(200, 40));
        btContasReceber.setMinimumSize(new java.awt.Dimension(200, 40));
        btContasReceber.setPreferredSize(new java.awt.Dimension(200, 40));
        btContasReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btContasReceberActionPerformed(evt);
            }
        });
        jToolBar1.add(btContasReceber);

        btFluxoCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/Calculator.png"))); // NOI18N
        btFluxoCaixa.setText("Fluxo de caixa");
        btFluxoCaixa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btFluxoCaixa.setFocusable(false);
        btFluxoCaixa.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btFluxoCaixa.setMaximumSize(new java.awt.Dimension(200, 40));
        btFluxoCaixa.setMinimumSize(new java.awt.Dimension(200, 40));
        btFluxoCaixa.setPreferredSize(new java.awt.Dimension(200, 40));
        btFluxoCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFluxoCaixaActionPerformed(evt);
            }
        });
        jToolBar1.add(btFluxoCaixa);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 0));
        jLabel7.setText("Relatório");
        jToolBar1.add(jLabel7);

        jbRelatorioVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/Report.png"))); // NOI18N
        jbRelatorioVendas.setText("Vendas");
        jbRelatorioVendas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jbRelatorioVendas.setFocusable(false);
        jbRelatorioVendas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbRelatorioVendas.setMaximumSize(new java.awt.Dimension(200, 40));
        jbRelatorioVendas.setMinimumSize(new java.awt.Dimension(200, 40));
        jbRelatorioVendas.setPreferredSize(new java.awt.Dimension(200, 40));
        jbRelatorioVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRelatorioVendasActionPerformed(evt);
            }
        });
        jToolBar1.add(jbRelatorioVendas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jPanel2.setBackground(new java.awt.Color(102, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setText("Alt+C = Clientes   -   Alt+P = Produtos   -   Alt+F = Fornecedor   -   Alt+V = Vendas   -   Alt+G = Contas Pagar   -    Alt+R = Contas a Receber");
        jPanel2.add(jLabel6);

        javax.swing.GroupLayout uJPanelImagem1Layout = new javax.swing.GroupLayout(uJPanelImagem1);
        uJPanelImagem1.setLayout(uJPanelImagem1Layout);
        uJPanelImagem1Layout.setHorizontalGroup(
            uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        uJPanelImagem1Layout.setVerticalGroup(
            uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Logado como:");

        jlUsuario.setText("usuaario");

        jlData.setText("data");

        jLabel5.setText("Data/Hora de login:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 492, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlData))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jlUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jlData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jmArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/Folder.png"))); // NOI18N
        jmArquivo.setText("Arquivo");

        jmiSobre.setText("Sobre o Sistema...");
        jmiSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSobreActionPerformed(evt);
            }
        });
        jmArquivo.add(jmiSobre);
        jmArquivo.add(jSeparator1);

        mnuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        mnuSair.setText("Sair");
        mnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSairActionPerformed(evt);
            }
        });
        jmArquivo.add(mnuSair);

        jMenuBar1.add(jmArquivo);

        jmCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/Create.png"))); // NOI18N
        jmCadastrar.setText("Cadastros");

        jmiClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jmiClientes.setText("Clientes");
        jmiClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiClientesActionPerformed(evt);
            }
        });
        jmCadastrar.add(jmiClientes);

        jmiProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jmiProdutos.setText("Produtos");
        jmiProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProdutosActionPerformed(evt);
            }
        });
        jmCadastrar.add(jmiProdutos);

        jmiFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        jmiFornecedor.setText("Fornecedores");
        jmiFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFornecedorActionPerformed(evt);
            }
        });
        jmCadastrar.add(jmiFornecedor);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Usuário");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmCadastrar.add(jMenuItem1);

        jMenuBar1.add(jmCadastrar);

        jmVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/Shopping cart.png"))); // NOI18N
        jmVendas.setText("Vendas");

        mnuRegistrarVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        mnuRegistrarVenda.setText("Vendas");
        mnuRegistrarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegistrarVendaActionPerformed(evt);
            }
        });
        jmVendas.add(mnuRegistrarVenda);

        jmiConsultarVenda.setText("Consultar vendas");
        jmiConsultarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsultarVendaActionPerformed(evt);
            }
        });
        jmVendas.add(jmiConsultarVenda);

        jmiPdv.setText("Vendas PDV");
        jmVendas.add(jmiPdv);

        jMenuBar1.add(jmVendas);

        jmFinanceiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/Dollar.png"))); // NOI18N
        jmFinanceiro.setText("Financeiro");

        jmiContasPagar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK));
        jmiContasPagar.setText("Conta a pagar");
        jmiContasPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiContasPagarActionPerformed(evt);
            }
        });
        jmFinanceiro.add(jmiContasPagar);

        jmiContasReceber.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        jmiContasReceber.setText("Contas a receber");
        jmiContasReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiContasReceberActionPerformed(evt);
            }
        });
        jmFinanceiro.add(jmiContasReceber);

        jmiFluxoCaixa.setText("Fluxo de caixa");
        jmiFluxoCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFluxoCaixaActionPerformed(evt);
            }
        });
        jmFinanceiro.add(jmiFluxoCaixa);

        jMenuBar1.add(jmFinanceiro);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/Report.png"))); // NOI18N
        jMenu1.setText("Relatórios");

        jmiRelClientes.setText("Clientes");
        jmiRelClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelClientesActionPerformed(evt);
            }
        });
        jMenu1.add(jmiRelClientes);

        jmiRelFornecedor.setText("Fornecedores");
        jmiRelFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelFornecedorActionPerformed(evt);
            }
        });
        jMenu1.add(jmiRelFornecedor);

        jmiRelProdutos.setText("Produtos");
        jmiRelProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelProdutosActionPerformed(evt);
            }
        });
        jMenu1.add(jmiRelProdutos);

        jmiRelatorioVendas.setText("Vendas por peíodo");
        jmiRelatorioVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelatorioVendasActionPerformed(evt);
            }
        });
        jMenu1.add(jmiRelatorioVendas);

        jmiRelatorioVenda.setText("Venda");
        jmiRelatorioVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelatorioVendaActionPerformed(evt);
            }
        });
        jMenu1.add(jmiRelatorioVenda);

        jMenuBar1.add(jMenu1);

        jmAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/Help.png"))); // NOI18N
        jmAjuda.setText("Ajuda");

        jMenuItem3.setText("Sobre");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jmAjuda.add(jMenuItem3);

        jMenuBar1.add(jmAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uJPanelImagem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(uJPanelImagem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSobreActionPerformed
        JOptionPane.showMessageDialog(null, "www.blsoft.com.br");
    }//GEN-LAST:event_jmiSobreActionPerformed

    private void mnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuSairActionPerformed

    private void jmiClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiClientesActionPerformed
        new ViewClientes().setVisible(true);
    }//GEN-LAST:event_jmiClientesActionPerformed

    private void jmiProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProdutosActionPerformed
        new ViewProduto().setVisible(true);
    }//GEN-LAST:event_jmiProdutosActionPerformed

    private void jmiFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFornecedorActionPerformed
        new ViewFornecedor().setVisible(true);
    }//GEN-LAST:event_jmiFornecedorActionPerformed

    private void mnuRegistrarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegistrarVendaActionPerformed
        new ViewVenda().setVisible(true);
    }//GEN-LAST:event_mnuRegistrarVendaActionPerformed

    private void jmiConsultarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsultarVendaActionPerformed
        ViewVenda venda = new ViewVenda();
        venda.setViewConsultarVendas();
        venda.setVisible(true);
    }//GEN-LAST:event_jmiConsultarVendaActionPerformed

    private void jmiRelClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelClientesActionPerformed
        // imprimir clientes
        ControllerCliente controllerCliente = new ControllerCliente();
        controllerCliente.gerarRelatorioCliente();
    }//GEN-LAST:event_jmiRelClientesActionPerformed

    private void jmiRelFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelFornecedorActionPerformed
        // imrimir fornecedores
        ControllerFornecedor controllerFornecedor = new ControllerFornecedor();
        controllerFornecedor.gerarRelatorioFornecedor();
    }//GEN-LAST:event_jmiRelFornecedorActionPerformed

    private void jmiRelProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelProdutosActionPerformed
        // imprimir produtos
        ControllerProdutos controllerProdutos = new ControllerProdutos();
        controllerProdutos.gerarRelatorioProdutos();
    }//GEN-LAST:event_jmiRelProdutosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new ViewUsuario().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btFluxoCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFluxoCaixaActionPerformed
        // acessar
        new ViewFluxoCaixa().setVisible(true);
    }//GEN-LAST:event_btFluxoCaixaActionPerformed

    private void btContasReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btContasReceberActionPerformed
        // acessar
        new ViewContasReceber().setVisible(true);
    }//GEN-LAST:event_btContasReceberActionPerformed

    private void btContaspagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btContaspagarActionPerformed
        // acessar
        new ViewContasPagar().setVisible(true);
    }//GEN-LAST:event_btContaspagarActionPerformed

    private void btRegistrarVenda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarVenda1ActionPerformed
        // TODO add your handling code here:
        new ViewPdv().setVisible(true);
    }//GEN-LAST:event_btRegistrarVenda1ActionPerformed

    private void btRegistrarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarVendaActionPerformed
        new ViewVenda().setVisible(true);
    }//GEN-LAST:event_btRegistrarVendaActionPerformed

    private void btUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUsuarioActionPerformed
        // TODO add your handling code here:
        new ViewUsuario().setVisible(true);
    }//GEN-LAST:event_btUsuarioActionPerformed

    private void btFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFornecedoresActionPerformed
        new ViewFornecedor().setVisible(true);
    }//GEN-LAST:event_btFornecedoresActionPerformed

    private void btProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProdutosActionPerformed
        new ViewProduto().setVisible(true);
    }//GEN-LAST:event_btProdutosActionPerformed

    private void btClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClientesActionPerformed
        new ViewClientes().setVisible(true);
    }//GEN-LAST:event_btClientesActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new ViewSobre(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jbRelatorioVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRelatorioVendasActionPerformed
        // TODO add your handling code here:
        new ViewRelatorioVendas().setVisible(true);
    }//GEN-LAST:event_jbRelatorioVendasActionPerformed

    private void jmiRelatorioVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelatorioVendasActionPerformed
        // TODO add your handling code here:
        new ViewRelatorioVendas().setVisible(true);
    }//GEN-LAST:event_jmiRelatorioVendasActionPerformed

    private void jmiRelatorioVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelatorioVendaActionPerformed
        // TODO add your handling code here:
        new ViewImprimirPDV(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jmiRelatorioVendaActionPerformed

    private void jmiContasPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiContasPagarActionPerformed
        // TODO add your handling code here:
        new ViewContasPagar().setVisible(true);
    }//GEN-LAST:event_jmiContasPagarActionPerformed

    private void jmiContasReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiContasReceberActionPerformed
        // TODO add your handling code here:
        new ViewContasReceber().setVisible(true);
    }//GEN-LAST:event_jmiContasReceberActionPerformed

    private void jmiFluxoCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFluxoCaixaActionPerformed
        // TODO add your handling code here:
        new ViewFluxoCaixa().setVisible(true);
    }//GEN-LAST:event_jmiFluxoCaixaActionPerformed

    public String retornarUsuarioLogado(){
        return new ModelSessaoUsuario().nome;
    }
    
    private void configurar(){
        pNomeUsuario = retornarUsuarioLogado();
        jlUsuario.setText(pNomeUsuario);
        BLDatas bLDatas = new BLDatas();
        jlData.setText(bLDatas.retornarDataHora());
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClientes;
    private javax.swing.JButton btContasReceber;
    private javax.swing.JButton btContaspagar;
    private javax.swing.JButton btFluxoCaixa;
    private javax.swing.JButton btFornecedores;
    private javax.swing.JButton btProdutos;
    private javax.swing.JButton btRegistrarVenda;
    private javax.swing.JButton btRegistrarVenda1;
    private javax.swing.JButton btUsuario;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jbRelatorioVendas;
    private javax.swing.JLabel jlData;
    private javax.swing.JLabel jlUsuario;
    private javax.swing.JMenu jmAjuda;
    private javax.swing.JMenu jmArquivo;
    private javax.swing.JMenu jmCadastrar;
    private javax.swing.JMenu jmFinanceiro;
    private javax.swing.JMenu jmVendas;
    private javax.swing.JMenuItem jmiClientes;
    private javax.swing.JMenuItem jmiConsultarVenda;
    private javax.swing.JMenuItem jmiContasPagar;
    private javax.swing.JMenuItem jmiContasReceber;
    private javax.swing.JMenuItem jmiFluxoCaixa;
    private javax.swing.JMenuItem jmiFornecedor;
    private javax.swing.JMenuItem jmiPdv;
    private javax.swing.JMenuItem jmiProdutos;
    private javax.swing.JMenuItem jmiRelClientes;
    private javax.swing.JMenuItem jmiRelFornecedor;
    private javax.swing.JMenuItem jmiRelProdutos;
    private javax.swing.JMenuItem jmiRelatorioVenda;
    private javax.swing.JMenuItem jmiRelatorioVendas;
    private javax.swing.JMenuItem jmiSobre;
    private javax.swing.JMenuItem mnuRegistrarVenda;
    private javax.swing.JMenuItem mnuSair;
    private componentes.UJPanelImagem uJPanelImagem1;
    // End of variables declaration//GEN-END:variables
}
